typography_spectrum: 0.367157022934407
content_rating:
  adult: false
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.001881839707493782
  lightness: 0.9402918615378439
  saturation: 0.19661546498537064
  rhythmicContrast: 0.12792377662844956
opengraph:
  type: ''
  appId: '1754348814853853'
layout_spectrum: 0.5869798169005662
analytics:
  google: UA-28506178-4
author:
  name: ''
  url: ''
  email: bluetail.in@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ddba1464-2ea0-42cd-8d3e-20396e7c6979.png
name: BlueTail
navigation:
  - name: Keep Yourself Motivated
    id: 04432c26-ccb4-4620-906f-b3b880614f72
    type: content
  - name: ‘The Law Of Non Resistance’
    id: 3f8856f0-87b7-4741-835a-80b50846df30
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2d71acb0-f008-40b7-be0c-293a3125ecb0.png
title: Positive Thinking For Everyday Life
