layout_spectrum: 0.45182221033610404
typography_spectrum: 0.4571722282562405
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.8737872820347548
  lightness: 0.36649449192918837
  saturation: 0.9756786364596337
  rhythmicContrast: 0.5659699079114944
content_rating:
  adult: false
opengraph:
  type: ''
  appId: '1754348814853853'
analytics:
  google: UA-28506178-4
author:
  name: ''
  url: ''
  email: bluetail.in@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ddba1464-2ea0-42cd-8d3e-20396e7c6979.png
name: BlueTail
navigation:
  - name: Keep Yourself Motivated
    id: 04432c26-ccb4-4620-906f-b3b880614f72
    type: content
  - name: ‘The Law Of Non Resistance’
    id: 3f8856f0-87b7-4741-835a-80b50846df30
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/2d71acb0-f008-40b7-be0c-293a3125ecb0.png
title: Positive Thinking For Everyday Life
